version: "3.1"
services:
  mariadb:
    image: mariadb:10.4.6
    restart: always
    env_file: .env
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./var/db:/var/lib/mysql
      - ./backup:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_USERNAME: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 81:80
    depends_on:
      - mariadb